# Generated by Django 3.0.1 on 2020-01-25 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0005_auto_20200109_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books_requested',
        ),
        migrations.AlterField(
            model_name='books_taken',
            name='taken_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 13, 5, 56, 550633), verbose_name='taken_on'),
        ),
    ]
