# Generated by Django 3.0.1 on 2020-01-25 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0006_auto_20200125_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_requested',
            fields=[
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='books_taken',
            name='taken_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 13, 8, 21, 187322), verbose_name='taken_on'),
        ),
    ]
