# Generated by Django 3.0.1 on 2020-01-25 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0007_auto_20200125_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_available',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=30)),
                ('book_genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='books_taken',
            name='taken_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 25, 13, 42, 33, 475406), verbose_name='taken_on'),
        ),
    ]
